# Generated by Django 6.0.1 on 2026-02-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_venta_created_by_venta_updated_by_ventaaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='stock_committed',
            field=models.BooleanField(default=False),
        ),
    ]
