# Generated by Django 6.0.1 on 2026-02-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_inventory_movement_adjustment'),
        ('inventario', '0012_producto_tipo_servicio'),
    ]

    operations = [
    ]
