# Generated by Codex
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_merge_20260206_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=80)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Lote de producto',
                'verbose_name_plural': 'Lotes de producto',
                'ordering': ['fecha_vencimiento', 'created_at'],
                'unique_together': {('producto', 'lote', 'fecha_vencimiento')},
            },
        ),
    ]
