# Generated by Django 6.0.1 on 2026-02-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_producto_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('VENTA', 'Venta'), ('ANULACION', 'Anulación')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('ACCESORIO', 'Accesorio'), ('SERVICIO', 'Servicio')], default='ACCESORIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='productolote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
