# Generated by Django 6.0.1 on 2026-02-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_inventorymovement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_global',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
