# Generated by Django 6.0.1 on 2026-02-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_saleitem_costo_unitario_venta_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': [('change_producto_stock', 'Puede ajustar stock de producto'), ('change_producto_precio', 'Puede cambiar precio de producto'), ('change_producto_costo', 'Puede cambiar costo de producto'), ('change_producto_lote', 'Puede cambiar lote/vencimiento de producto')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
