# Generated by Django 6.0.1 on 2026-02-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_producto_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
