# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_staff_telefono_ownerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='documento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='genero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='genero',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
