# Generated by Django 6.0.1 on 2026-02-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_staff_owner_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='cargo',
            field=models.CharField(choices=[('VETERINARIO', 'Veterinario'), ('ADMIN', 'Administrador'), ('ASISTENTE', 'Asistente'), ('INVENTARIO', 'Inventario')], max_length=20),
        ),
    ]
