# Generated by Codex
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_cita_origen'),
        ('inventario', '0014_producto_lote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('USADO', 'Usado'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_lote', to='clinica.consulta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_lote', to='clinica.expediente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='inventario.productolote')),
            ],
            options={
                'verbose_name': 'Reserva de lote',
                'verbose_name_plural': 'Reservas de lote',
                'ordering': ['-created_at'],
            },
        ),
    ]
