# Generated by Codex
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_reserva_lote'),
        ('inventario', '0014_producto_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservalote',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_lote', to='inventario.venta'),
        ),
    ]
