# Generated by Django 6.0.1 on 2026-02-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_alter_cita_estado'),
        ('clinica', '0009_reserva_lote'),
    ]

    operations = [
    ]
