# Generated by Django 6.0.1 on 2026-02-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_merge_0009_alter_cita_estado_0009_reserva_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservalote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
