# Generated by Django 6.0.1 on 2026-02-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_reserva_lote_venta'),
        ('clinica', '0011_alter_reservalote_id'),
    ]

    operations = [
    ]
