# Generated by Django 6.0.1 on 2026-02-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0013_update_cita_reminder_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citareminder',
            name='canal',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp')], max_length=20),
        ),
    ]
