from django.urls import path
from .views import (
    ProductoCreateView, ProductoListView, ProductoUpdateView, ProductoToggleActiveView, ProductoDetailView,
    VentaCreateView, VentaListView, VentaDetailView, VentaUpdateView, VentaDeleteView, VentaReceiptView,
    VentaConfigUpdateView,
    product_autocomplete, VentaAuditListView,
    RecordatorioListView, RecordatorioCreateView, RecordatorioUpdateView, RecordatorioDeleteView,
    RecordatorioCompleteView,
    SolicitudAnulacionCreateView, SolicitudAnulacionListView, SolicitudAnulacionApproveView, SolicitudAnulacionRejectView,
    InventoryMovementListView, StockAdjustmentRequestListView, StockAdjustmentRequestCreateView,
    StockAdjustmentApproveView, StockAdjustmentRejectView, LotesVencerListView,
    ReportesView,
    ProductoDescuentoListView, ProductoDescuentoDisableView, ProductoDescuentoCreateView, ProductoDescuentoUpdateView,
    TipoDescuentoUpdateView, TipoDescuentoDisableView,
)

app_name = 'inventario'

urlpatterns = [
    path('', ProductoListView.as_view(), name='list'),
    path('nuevo/', ProductoCreateView.as_view(), name='create'),
    path('<int:pk>/editar/', ProductoUpdateView.as_view(), name='producto_update'),
    path('producto/<int:pk>/', ProductoDetailView.as_view(), name='producto_detail'),
    path('<int:pk>/toggle/', ProductoToggleActiveView.as_view(), name='producto_toggle'),
    path('ventas/', VentaListView.as_view(), name='venta_list'),
    path('ventas/nuevo/', VentaCreateView.as_view(), name='venta_create'),
    path('ventas/<int:pk>/', VentaDetailView.as_view(), name='venta_detail'),
    path('ventas/<int:pk>/recibo/', VentaReceiptView.as_view(), name='venta_receipt'),
    path('ventas/<int:pk>/editar/', VentaUpdateView.as_view(), name='venta_update'),
    path('ventas/<int:pk>/eliminar/', VentaDeleteView.as_view(), name='venta_delete'),
    path('ventas/<int:pk>/anular/solicitar/', SolicitudAnulacionCreateView.as_view(), name='venta_anulacion_request'),
    path('ventas/anulaciones/', SolicitudAnulacionListView.as_view(), name='anulacion_list'),
    path('ventas/anulaciones/<int:pk>/aprobar/', SolicitudAnulacionApproveView.as_view(), name='anulacion_approve'),
    path('ventas/anulaciones/<int:pk>/rechazar/', SolicitudAnulacionRejectView.as_view(), name='anulacion_reject'),
    path('ventas/configuracion/', VentaConfigUpdateView.as_view(), name='venta_config'),
    path('api/products/', product_autocomplete, name='api_products'),
    path('audits/', VentaAuditListView.as_view(), name='venta_audit_list'),
    path('kardex/', InventoryMovementListView.as_view(), name='kardex_list'),
    path('lotes/vencer/', LotesVencerListView.as_view(), name='lotes_vencer'),
    path('reportes/', ReportesView.as_view(), name='reportes'),
    path('ajustes/', StockAdjustmentRequestListView.as_view(), name='ajuste_list'),
    path('ajustes/nuevo/', StockAdjustmentRequestCreateView.as_view(), name='ajuste_create'),
    path('ajustes/<int:pk>/aprobar/', StockAdjustmentApproveView.as_view(), name='ajuste_approve'),
    path('ajustes/<int:pk>/rechazar/', StockAdjustmentRejectView.as_view(), name='ajuste_reject'),
    path('recordatorios/', RecordatorioListView.as_view(), name='recordatorio_list'),
    path('recordatorios/nuevo/', RecordatorioCreateView.as_view(), name='recordatorio_create'),
    path('recordatorios/<int:pk>/editar/', RecordatorioUpdateView.as_view(), name='recordatorio_update'),
    path('recordatorios/<int:pk>/eliminar/', RecordatorioDeleteView.as_view(), name='recordatorio_delete'),
    path('recordatorios/<int:pk>/completar/', RecordatorioCompleteView.as_view(), name='recordatorio_complete'),
    path('descuentos/', ProductoDescuentoListView.as_view(), name='producto_descuentos'),
    path('descuentos/nuevo/', ProductoDescuentoCreateView.as_view(), name='producto_descuento_create'),
    path('descuentos/<int:pk>/editar/', ProductoDescuentoUpdateView.as_view(), name='producto_descuento_update'),
    path('descuentos/<int:pk>/desactivar/', ProductoDescuentoDisableView.as_view(), name='producto_descuento_disable'),
    path('descuentos/tipo/<str:tipo>/editar/', TipoDescuentoUpdateView.as_view(), name='tipo_descuento_update'),
    path('descuentos/tipo/<str:tipo>/desactivar/', TipoDescuentoDisableView.as_view(), name='tipo_descuento_disable'),
]
