from django.urls import path
from .views import (
    DashboardView, ExpedienteDetailView, ConsultaCreateView,
    MascotaUpdateView, MascotaCreateView, MascotaListView,
    CitaCreateView, CitaListView, CitaDetailView,
    CitaUpdateView, CitaCalendarView, CitaEventsView,
    CitaStatusUpdateView,
    CitaHistoryListView,
    SolicitudCitaCreateView, SolicitudCitaListView, SolicitudCitaApproveView,
    SolicitudReprogramacionCreateView, SolicitudReprogramacionListView, SolicitudReprogramacionApproveView,
    SolicitudReprogramacionUpdateView,
    RecetaApproveView, RecetaRejectView, RecetaPrintView,
    ReportesView,
    ReservaLoteCreateView, ReservaLoteCancelView, ReservaLoteUseView,
    CitaReminderGenerateView, CitaReminderListView, CitaReminderSwitchChannelView,
)

app_name = 'clinica'

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('expediente/<int:pk>/', ExpedienteDetailView.as_view(), name='expediente_detail'),
    path('expediente/<int:pk>/reservar-lote/', ReservaLoteCreateView.as_view(), name='reserva_lote_create'),
    path('reserva-lote/<int:pk>/cancelar/', ReservaLoteCancelView.as_view(), name='reserva_lote_cancel'),
    path('reserva-lote/<int:pk>/usar/', ReservaLoteUseView.as_view(), name='reserva_lote_use'),
    path('citas/', CitaListView.as_view(), name='cita_list'),
    path('citas/historial/', CitaHistoryListView.as_view(), name='cita_history_list'),
    path('citas/calendario/', CitaCalendarView.as_view(), name='cita_calendar'),
    path('citas/calendario/eventos/', CitaEventsView.as_view(), name='cita_events'),
    path('citas/recordatorios/generar/', CitaReminderGenerateView.as_view(), name='cita_reminders_generate'),
    path('citas/recordatorios/', CitaReminderListView.as_view(), name='cita_reminder_list'),
    path('citas/recordatorios/<int:pk>/canal/whatsapp/', CitaReminderSwitchChannelView.as_view(), name='cita_reminder_whatsapp'),
    path('citas/nueva/', CitaCreateView.as_view(), name='cita_create'),
    path('citas/<int:pk>/editar/', CitaUpdateView.as_view(), name='cita_edit'),
    path('citas/<int:pk>/estado/', CitaStatusUpdateView.as_view(), name='cita_status'),
    path('citas/<int:pk>/', CitaDetailView.as_view(), name='cita_detail'),
    path('citas/<int:pk>/consulta/nueva/', ConsultaCreateView.as_view(), name='agregar_consulta'),
    path('recetas/<int:pk>/aprobar/', RecetaApproveView.as_view(), name='receta_approve'),
    path('recetas/<int:pk>/rechazar/', RecetaRejectView.as_view(), name='receta_reject'),
    path('recetas/<int:pk>/imprimir/', RecetaPrintView.as_view(), name='receta_print'),
    path('solicitudes-citas/', SolicitudCitaListView.as_view(), name='solicitud_cita_list'),
    path('solicitudes-citas/nueva/', SolicitudCitaCreateView.as_view(), name='solicitud_cita_create'),
    path('solicitudes-citas/<int:pk>/aprobar/', SolicitudCitaApproveView.as_view(), name='solicitud_cita_approve'),
    path('reprogramaciones/', SolicitudReprogramacionListView.as_view(), name='solicitud_reprogramacion_list'),
    path('citas/<int:pk>/reprogramar/', SolicitudReprogramacionCreateView.as_view(), name='solicitud_reprogramacion_create'),
    path('reprogramaciones/<int:pk>/aprobar/', SolicitudReprogramacionApproveView.as_view(), name='solicitud_reprogramacion_approve'),
    path('reprogramaciones/<int:pk>/editar/', SolicitudReprogramacionUpdateView.as_view(), name='solicitud_reprogramacion_edit'),
    path('mascota/<int:pk>/editar/', MascotaUpdateView.as_view(), name='editar_mascota'),
    path('mascota/nueva/', MascotaCreateView.as_view(), name='crear_mascota'),
    path('mascotas/', MascotaListView.as_view(), name='lista_mascotas'),
    path('reportes/', ReportesView.as_view(), name='reportes'),
]
